# Generated by Django 3.2.21 on 2023-09-21 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_mzto5w', upload_to='images/')),
                ('travel', models.CharField(choices=[('bicycle', 'Bicycle'), ('boat', 'Boat'), ('foot', 'By Foot'), ('car', 'Combustion Engine Car'), ('electric', 'Electric Car'), ('multiple', 'Multiple'), ('other', 'Other'), ('plane', 'Plane'), ('train', 'Train')], default='multiple', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
